name: SmartFocusAI Pipeline

# Déclenche le workflow à chaque push et PR sur n'importe quelle branche
on:
  push:    {}
  pull_request: {}

jobs:
  test:
    # machine virtuelle Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1) Récupère le code
      - uses: actions/checkout@v3

      # 2) Installe Python 3.10
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Installe tes dépendances
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4) Lance les tests unitaires
      - name: Unit tests
        run: |
          pytest tests/unit -v

      # 5) Lance les tests d'intégration
      - name: Integration tests
        run: |
          pytest -m integration -v

