# .github/workflows/ci.yml

name: SmartFocusAI Pipeline

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    # 1) Définition unique du token ici :
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install -e .

      - name: Run tests & collect coverage
        run: |
          xvfb-run -a pytest tests/unit tests/integration \
          --cov=src \
          --cov-report=term-missing \
          --cov-report=xml:coverage.xml \

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: tests
          fail_ci_if_error: true
